Repository andela/caret-bn-backend, pull requests merged in 2019-10, with the labels that each got.

#1 Chore(Coverage): Integrate Coveralls Code coverage
  .gitignore
  README.md
  package-lock.json
  package.json
Labels: Awaiting Approval

#3 #168781670 Setting up dotenv
  .env.example
  package-lock.json
  src/index.js
Labels: Ready For Review

#2 chore(configure eslint):
  .eslintignore
  .eslintrc.json
  package-lock.json
  package.json
  src/index.js
Labels: Ready For Review

#4 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Awaiting Approval

#5 #168781667 Setup Unit Testing
  .babelrc
  .eslintrc.json
  package-lock.json
  package.json
  src/index.js
  src/tests/test.js
Labels: Ready For Review

#7 #168781666 Integrate Travis CI
  .travis.yml
  README.md
Labels: Awaiting Approval

#6 #168781663 set sequelize and postgres sql
  .babelrc
  .env.example
  .eslintrc.json
  .sequelizerc
  .travis.yml
  package-lock.json
  package.json
  src/config/passport.js
  src/database/config.js
  src/database/migrations/20190930143254-User.js
  src/database/models/index.js
  src/database/models/users.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/models/User.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/index.js
  src/services/userServices.js
  src/tests/test.js
Labels: Ready For Review

#15 #168928511 integrate code climate
  README.md
Labels: Awaiting Approval

#13 #168781672 - Setting up Swagger Documentation
  .babelrc
  .gitignore
  package-lock.json
  package.json
  src/database/config.js
  src/index.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/index.js
  src/routes/swagger-doc.js
  src/tests/test.js
Labels: Ready For Review

#16 #168968279 - Fixing Deployment to Heroku
  Procfile
  README.md
  package.json
  src/routes/swagger-doc.js
Labels: Awaiting Approval, Ready For Review

#14 #168781673 - Set up docker
  .dockerignore
  .env.example
  .gitignore
  .travis.yml
  .vscode/settings.json
  Dockerfile
  README.md
  docker-compose.prod.yml
  docker-compose.yml
  package-lock.json
  package.json
  src/database/config.js
Labels: Ready For Review

#17 #168781674 Deploy base app to heroku
  .gitignore
  app.json
  package-lock.json
  package.json
  src/database/app.json
  src/database/config.js
  src/routes/swagger-doc.js
Labels: Ready For Review

#18 #168781675 - Signup/Register feature
  .babelrc
  .env.example
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/controllers/userController.js
  src/database/migrations/20191007121953-addPasswordAndVerificationColumns.js
  src/database/models/users.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/middlewares/checkSignup.js
  src/middlewares/confirmPassword.js
  src/middlewares/verifyExist.js
  src/routes/api/users.js
  src/routes/swagger-doc.js
  src/tests/mockdata.js
  src/tests/signupTest.spec.js
  src/tests/test.js
  src/utils/generateToken.js
  src/utils/hashPassword.js
  src/utils/responseError.js
  src/utils/responseUtil.js
  src/utils/stringsUtil.js
  src/utils/verifyUserExist.js
  src/validation/validateSignup.js
Labels: Ready For Review

#19 #168781679 User Login
  .eslintignore
  package-lock.json
  package.json
  src/controllers/userController.js
  src/database/config.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/index.js
  src/middlewares/checkLogin.js
  src/routes/api/users.js
  src/routes/swagger-doc.js
  src/tests/index.js
  src/tests/loginTest.js
  src/tests/mockData/mockData.js
  src/utils/stringsUtil.js
  src/validation/validateLogin.js
Labels: Ready For Review

#20 #168781676-email signup verification feature
  package-lock.json
  package.json
  src/controllers/userController.js
  src/database/config.js
  src/routes/api/users.js
  src/tests/mockdata.js
  src/tests/signupTest.spec.js
  src/utils/generateToken.js
  src/utils/stringsUtil.js
Labels: Ready For Review

#23 #169107967 - Fixing Heroku database
  .env.example
  package-lock.json
  package.json
  src/database/config.js
  src/index.js
  src/routes/swagger-doc.js
Labels: Ready For Review

#22 Ft social media signin 168781680
  .env.example
  .eslintignore
  .eslintrc.json
  .travis.yml
  .vscode/settings.json
  docker-compose.yml
  package-lock.json
  package.json
  src/config/social/config.js
  src/controllers/auth/socialAuthenticationController.js
  src/database/migrations/20191007121953-addPasswordAndVerificationColumns.js
  src/database/migrations/20191007150358-addOAuthFields.js
  src/database/migrations/20191008081400-addFacebookOAuthFields.js
  src/database/migrations/20191008084043-changeEmailToNullable.js
  src/database/models/users.js
  src/index.js
  src/middlewares/auth/tokenMiddleware.js
  src/middlewares/errorHandler.js
  src/routes/api/auth/index.js
  src/routes/api/auth/social/facebook.js
  src/routes/api/auth/social/google.js
  src/routes/api/index.js
  src/routes/swagger-doc.js
  src/services/serviceHelpers/userServiceHelpers.js
  src/services/userServices.js
  src/tests/defaultTests.spec.js
  src/tests/index.js
  src/tests/index.spec.js
  src/tests/loginTest.spec.js
  src/tests/mockData/signupMockdata.js
  src/tests/signupTest.spec.js
  src/tests/socialAuthTests.spec.js
  src/utils/db/queryScopes.js
  src/utils/index.js
  src/utils/passport/strategyQueries.js
  src/utils/responseHelper.js
  src/utils/secure/socialAuthKeys.js
  src/utils/secure/socialStrategy.js
  src/utils/strings.js
  src/utils/tokenHelper.js
Labels: Ready For Review

#21 #168781681 -User can reset password
  package-lock.json
  package.json
  src/controllers/userController.js
  src/middlewares/checkResetpassword.js
  src/routes/api/users.js
  src/tests/mockData/signupMockdata.js
  src/tests/signupTest.spec.js
  src/utils/EmailToken.js
  src/utils/stringsUtil.js
  src/validation/validateResetpassword.js
Labels: Ready For Review

#24 Ft integrate requests trips 168781688
  .eslintrc.json
  src/controllers/requestController.js
  src/database/migrations/20191015081627-create-requests.js
  src/database/migrations/20191015081823-create-trip-types.js
  src/database/migrations/20191015081900-create-request-status.js
  src/database/migrations/20191015081937-create-locations.js
  src/database/migrations/20191015082308-create-destinations.js
  src/database/models/destinations.js
  src/database/models/locations.js
  src/database/models/requests.js
  src/database/models/requeststatus.js
  src/database/models/triptypes.js
  src/database/models/users.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/database/seeders/20191015080808-loationsTableSeeder.js
  src/database/seeders/20191015080824-tripTypesTableSeeder.js
  src/database/seeders/20191015082849-requestStatusSeeder.js
  src/database/seeders/20191016143026-requestTableSeeder.js
  src/database/seeders/20191016143055-destinationsTableSeeder.js
  src/middlewares/auth/validateToken.js
  src/routes/api/index.js
  src/routes/api/requests.js
  src/services/userServices.js
  src/tests/index.spec.js
  src/tests/mockData/mockData.js
  src/tests/requestTests.spec.js
  src/tests/socialAuthTests.spec.js
  src/utils/db/queries/requestQueries.js
  src/utils/index.js
  src/utils/strings.js
Labels: Ready For Review

#25 #168781707 create and view accommodation
  .env.example
  .eslintignore
  package-lock.json
  package.json
  src/controllers/accommodationController.js
  src/database/migrations/20191007121953-addPasswordAndVerificationColumns.js
  src/database/migrations/20191015083831-create-accommodations.js
  src/database/models/accommodations.js
  src/database/models/users.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/helpers/imagesHelper.js
  src/middlewares/checkLogin.js
  src/middlewares/checkRole.js
  src/middlewares/inputValidation.js
  src/routes/api/accommodations.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/tests/accommodationTest.spec.js
  src/tests/index.spec.js
  src/tests/mockData/AI.png
  src/tests/mockData/AI2.png
  src/tests/mockData/mockData.js
  src/utils/generateToken.js
  src/utils/stringsUtil.js
  src/validation/validateLogin.js
Labels: Ready For Review

#27 #169113466 - Edit and Delete Accommodation Facilities
  package-lock.json
  src/controllers/accommodationController.js
  src/database/migrations/20191015091939-create-locations.js
  src/database/migrations/20191017165632-create-accommodations.js
  src/database/models/accommodations.js
  src/database/models/locations.js
  src/database/seeders/20191016080543-accommodationsTableSeeder.js
  src/helpers/imageUploader.js
  src/middlewares/catchEmptyForm.js
  src/middlewares/checkId.js
  src/middlewares/checkSignup.js
  src/middlewares/inputValidation.js
  src/middlewares/isAccommodationFound.js
  src/middlewares/isOwner.js
  src/routes/api/accommodations.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/swagger-doc.js
  src/services/accommodationServices.js
  src/tests/accommodationTest.spec.js
  src/tests/editDeleteAccommodationsTests.spec.js
  src/tests/index.spec.js
  src/tests/mockData/accommodationData.js
  src/tests/socialAuthTests.spec.js
  src/utils/stringsUtil.js
  src/validation/idValidator.js
  src/validation/validateSignup.js
Labels: Ready For Review

#26 #168781683 user profile setting
  src/controllers/profileController.js
  src/database/migrations/20190930143254-User.js
  src/database/models/users.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/middlewares/inputValidation.js
  src/middlewares/users.js
  src/routes/api/users.js
  src/tests/index.spec.js
  src/tests/mockData/mockData.js
  src/tests/mockData/signupMockdata.js
  src/tests/profile.spec.js
  src/tests/requestTests.spec.js
  src/tests/signupTest.spec.js
  src/utils/generateToken.js
  src/utils/strings.js
  src/utils/stringsUtil.js
  src/utils/tokenHelper.js
Labels: Ready For Review

#29 #169228237 view accommodations under one route
  .eslintignore
  .gitignore
  package-lock.json
  package.json
  src/controllers/accommodationController.js
  src/database/migrations/20191017165632-create-accommodations.js
  src/database/models/accommodations.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/database/seeders/20191016080543-accommodationsTableSeeder.js
  src/middlewares/checkRole.js
  src/middlewares/inputValidation.js
  src/middlewares/isAccommodationFound.js
  src/routes/api/accommodations.js
  src/tests/accommodationTest.spec.js
  src/tests/mockData/mockData.js
  src/utils/stringsUtil.js
Labels: Ready For Review

#30 #168781691 approve/reject request
  package.json
  src/controllers/requestController.js
  src/database/migrations/20190930143254-User.js
  src/database/migrations/20191007121953-addPasswordAndVerificationColumns.js
  src/database/models/requests.js
  src/database/models/users.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/helpers/findRequests.js
  src/middlewares/checkRole.js
  src/middlewares/inputValidation.js
  src/routes/api/requests.js
  src/tests/mockData/mockData.js
  src/tests/requestTests.spec.js
  src/utils/strings.js
  src/utils/stringsUtil.js
Labels: Awaiting Approval

#33 #168781697 - Add Search Functionality on Requests
  .codeclimate.yml
  package.json
  src/controllers/requestController.js
  src/database/migrations/20190930143254-User.js
  src/database/migrations/20191007121953-addPasswordAndVerificationColumns.js
  src/database/migrations/20191015081627-create-requests.js
  src/database/migrations/20191021111956-addBookingIdToDestination.js
  src/database/migrations/20191023093805-addDepartureAndReturnToRequests.js
  src/database/models/destinations.js
  src/database/models/requests.js
  src/database/models/users.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/database/seeders/20191016143026-requestTableSeeder.js
  src/database/seeders/20191016143055-destinationsTableSeeder.js
  src/middlewares/catchSearchQueries.js
  src/middlewares/checkRole.js
  src/middlewares/checkUserIdField.js
  src/middlewares/inputValidation.js
  src/middlewares/managerUserIdField.js
  src/routes/api/requests.js
  src/services/searchRequestsServices.js
  src/tests/editDeleteAccommodationsTests.spec.js
  src/tests/index.spec.js
  src/tests/mockData/mockData.js
  src/tests/searchRequestsTests.spec.js
  src/utils/requestsSearch.js
  src/utils/strings.js
  src/utils/stringsUtil.js
Labels: Ready For Review

#35 #169385153 add slugs to accommodations
  package-lock.json
  package.json
  src/controllers/accommodationController.js
  src/database/migrations/20190930143254-User.js
  src/database/migrations/20191015081823-create-trip-types.js
  src/database/migrations/20191015081900-create-request-status.js
  src/database/migrations/20191015082308-create-destinations.js
  src/database/migrations/20191015091939-create-locations.js
  src/database/migrations/20191016090432-create-role.js
  src/database/migrations/20191017165632-create-accommodations.js
  src/database/models/accommodations.js
  src/database/models/destinations.js
  src/database/models/users.js
Labels: Awaiting Approval

#32 #168781708-user can book an accommodation
  package-lock.json
  package.json
  src/controllers/accommodationController.js
  src/database/migrations/20191017165632-create-accommodations.js
  src/database/migrations/20191023121501-create-booking.js
  src/database/models/accommodations.js
  src/database/models/booking.js
  src/database/seeders/20191016080543-accommodationsTableSeeder.js
  src/helpers/bookingHelper.js
  src/helpers/checkDateHelper.js
  src/middlewares/checkRole.js
  src/middlewares/inputValidation.js
  src/routes/api/accommodations.js
  src/tests/accommodationTest.spec.js
  src/tests/adminTest.spec.js
  src/tests/mockData/mockData.js
  src/tests/signupTest.spec.js
  src/utils/stringsUtil.js
Labels: Ready For Review

#31 Ft user make request 168781684
  .vscode/settings.json
  package-lock.json
  package.json
  src/controllers/destinationController.js
  src/controllers/requestController.js
  src/database/models/destinations.js
  src/database/models/requests.js
  src/database/seeders/20191016143026-requestTableSeeder.js
  src/database/seeders/20191029101737-bookingsSeeder.js
  src/helpers/datesValidator.js
  src/middlewares/requests/bookingsVerification.js
  src/middlewares/requests/datesVerification.js
  src/middlewares/requests/destinationVerification.js
  src/middlewares/requests/locationVerification.js
  src/middlewares/requests/relationVerification.js
  src/middlewares/requests/tripTypesVerification.js
  src/routes/api/requests.js
  src/services/requestServices/destinationServices.js
  src/services/requestServices/index.js
  src/services/requestServices/locationServices.js
  src/services/requestServices/requestServices.js
  src/services/requestServices/tripTypeServices.js
  src/tests/index.spec.js
  src/tests/mockData/requestData.js
  src/tests/requestTests/index.spec.js
  src/tests/requestTests/requestCreationTest.spec.js
  src/utils/db/queries/requestQueries.js
  src/utils/db/queries/userQueries.js
  src/utils/index.js
  src/utils/validationErrorFormatter.js
  src/validation/validateRequest.js
Labels: Ready For Review

#34 #168781705 - Edit trip request
  package-lock.json
  src/controllers/commentsController.js
  src/controllers/requestController.js
  src/database/migrations/20191029094504-create-comments.js
  src/database/models/comments.js
  src/database/seeders/20191016143026-requestTableSeeder.js
  src/database/seeders/20191016143055-destinationsTableSeeder.js
  src/database/seeders/20191029103632-comments.js
  src/helpers/requestHelper.js
  src/middlewares/inputValidation.js
  src/middlewares/request.js
  src/middlewares/requests/relationVerification.js
  src/routes/api/requests.js
  src/tests/accommodationTest.spec.js
  src/tests/editRequest.spec.js
  src/tests/index.spec.js
  src/tests/mockData/mockData.js
  src/tests/mockData/requestData.js
  src/tests/profile.spec.js
  src/tests/requestTests/requestCreationTest.spec.js
  src/utils/stringsUtil.js
Labels: Ready For Review

#37 #168781687 - Send Notifications
  .env.example
  package-lock.json
  package.json
  src/controllers/destinationController.js
  src/controllers/notificationController.js
  src/controllers/requestController.js
  src/controllers/userController.js
  src/database/migrations/20191028100501-create-notifications.js
  src/database/migrations/20191028101515-AddEmailNotifToUser.js
  src/database/models/notifications.js
  src/database/models/users.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/database/seeders/20191028170529-notificationsTableSeeder.js
  src/helpers/alreadyProcessed.js
  src/helpers/findOneRequest.js
  src/helpers/findRequests.js
  src/helpers/findUser.js
  src/helpers/notifSender.js
  src/middlewares/isProcessed.js
  src/middlewares/wrongAction.js
  src/routes/api/index.js
  src/routes/api/notifications.js
  src/routes/api/requests.js
  src/routes/api/users.js
  src/services/notifServices.js
  src/tests/index.spec.js
  src/tests/notificationsTests.spec.js
  src/tests/requestTests.spec.js
  src/utils/generateToken.js
  src/utils/stringsUtil.js
Labels: Ready For Review

#36 #168781703 travel admins can add accommodations
  .codeclimate.yml
  src/controllers/accommodationController.js
  src/database/migrations/20191017165632-create-accommodations.js
  src/database/models/accommodations.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/database/seeders/20191016080543-accommodationsTableSeeder.js
  src/database/seeders/20191029101737-bookingsSeeder.js
  src/helpers/emailHelper.js
  src/helpers/getAccommodation.js
  src/helpers/imageUploader.js
  src/middlewares/checkRole.js
  src/middlewares/inputValidation.js
  src/routes/api/accommodations.js
  src/tests/accommodationTest.spec.js
  src/tests/mockData/mockData.js
  src/tests/requestTests/requestCreationTest.spec.js
  src/utils/stringsUtil.js
Labels: Awaiting Approval

#39 FT (Users add ratings): A user must add ratings against an accomodation
  package.json
  src/controllers/accommodationController.js
  src/controllers/ratingsController.js
  src/database/migrations/20191030072352-create-ratings.js
  src/database/models/accommodations.js
  src/database/models/ratings.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/database/seeders/20191016080543-accommodationsTableSeeder.js
  src/helpers/getAccommodation.js
  src/helpers/ratingsHelper.js
  src/middlewares/ratingsMiddleware.js
  src/routes/api/index.js
  src/routes/api/ratings.js
  src/services/accommodationServices.js
  src/services/bookingServices.js
  src/services/ratingsServices.js
  src/tests/adminTest.spec.js
  src/tests/index.spec.js
  src/tests/ratingsTests.spec.js
  src/tests/requestTests/index.spec.js
  src/tests/requestTests/requestCreationTest.spec.js
  src/tests/requestTests/unitTests/verifyBookings.spec.js
  src/utils/db/queries/bookingQueries.js
  src/validation/validateRating.js
Labels: Ready For Review

#41 #169469189 - Opt-in/out app notifications
  .env.example
  src/controllers/destinationController.js
  src/controllers/requestController.js
  src/controllers/userController.js
  src/database/migrations/20191031061524-addAppNotifToUser.js
  src/database/models/users.js
  src/database/seeders/20191002153158-usersTableSeeder.js
  src/helpers/notifSender.js
  src/helpers/updateUser.js
  src/middlewares/wrongAction.js
  src/middlewares/wrongSwitch.js
  src/routes/api/users.js
  src/tests/notificationsTests.spec.js
  src/utils/stringsUtil.js
Labels: Ready For Review
